### PR TITLE
V2 - Rewrite

### PR DESCRIPTION
**Pull request by hjbdev**
- Rewritten pvm in Golang
- Added installation command

### CODE REVIEW

**Comment by husseinalhammad** [comment]
Thanks for the quick response, @hjbdev. My exposure to Go has been minimal, but I'm interested to pick this up.

It would be great to have an overview of what has been done and what is yet to be done. It looks like you already implemented the following commands:

- `help`
- `install` (Windows only)

And the following commands are yet to be implemented:

- `discover`
- `list`
- `path` - removed from the list of commands `help` returns. Is this deprecated?


Is the above correct? 

And is the scope for this PR to get to work for Windows only? Seeing #2 makes me wonder whether the plan is to add MacOS support for v2 right away (or whether that's a v2.1 feature).

**Comment by hjbdev** [comment]
no worries, yeah `help` and `install` are already implemented, `install` may need a look over but I think most of it is done. `path` will still need to be implemented I think due to the way pvm works at its core, with a symlink that dynamically changes based on the php version currently in use. There may be a better way to do this though?

Windows only for the initial v2 would probably be best, keep it simple. I don't have access to a MacOS machine now so wouldn't be able to implement or really help in any way there.

**Comment by husseinalhammad** [comment]
Noted.

I have access to both Windows and Mac (and have to switch between the two). My team uses both Windows and Mac, and Docker is a bit of an overkill for our use cases. So I'm interested to help shape PVM to become a lightweight cross-platform PHP version manager.

**Comment by rymesaint** [comment]
how to add custom extension for php?

**Pull request merged**
